

#\u5F00\u53D1\u73AF\u5883\u6570\u636E\u5E93\u4FE1\u606F
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_learn?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Ly818379   #\u6570\u636E\u5E93\u540D\u3001\u7528\u6237\u540D\u548C\u5BC6\u7801\u6539\u4E3A\u81EA\u5DF1\u7684
    driver-class-name: com.mysql.cj.jdbc.Driver
