#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9761/eureka #Eureka服务跟客户端交互的地址
    register-with-eureka: false # 是否将自己注册到Eureka 服务中
    fetch-registry: false #是否从Eureka服务中获取信息
  server:
    enable-self-preservation: false  #自我保护，client启动台频繁，server端会发出警告：开发环境可以使用，生产环境一定要注释
spring:
  application:
    name: eureka
server:
  port: 9761
